version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        GIT_NAME: $GIT_NAME
        GIT_EMAIL: $GIT_EMAIL
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      - .:/data
